asset_path: /home/zdli/Piper-Grasper/src/piper_grasper/desk/../../../assets/workDesk_v1/workDesk_v1.stl
usd_dir: /home/zdli/Piper-Grasper/src/piper_grasper/desk/../../../assets/workDesk_v1
usd_file_name: workDesk_v1.usd
force_usd_conversion: true
make_instanceable: true
mass_props:
  mass: null
  density: 200.0
rigid_props:
  rigid_body_enabled: false
  kinematic_enabled: false
  disable_gravity: null
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
collision_approximation: meshSimplification
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 0.7071067690849304
- 0.0
- 0.0
- -0.7071067690849304
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2025-08-29 at 20:24:09.
##
